name: testing my github action skills
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:

env:
    REF: ${{github.ref}}

jobs:
    helloWorld:
        runs-on: ubuntu-latest
        steps:
            - name: hello user
              if: ${{github.ref_name == 'master'}}
              run: echo "hello ${{github.ref_name}}"

    going_To_University:
        runs-on: ubuntu-latest
        needs: helloWorld
        steps: 
            - name: hungry 
              run: echo "eat breakfast"
            - name: going out
              run: echo "on my way to the uneversity" 


    goodbye:
        runs-on: ubuntu-latest
        needs: 
            - helloWorld
            - going_To_University
        steps:
            - name: goodbye
              run: echo "goodbye sir"
        if: ${{always()}}

    
              
