name: testing my github action skills
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:

env:
    NAME: anouer

jobs:
    helloWorld:
        runs-on: ubuntu-latest
        steps:
            - name: hello user
              run: echo "hello $name"

    
    goodbye:
        runs-on: ubuntu-latest
        needs: helloWorld
        steps:
            - name: goodbye
              run: echo "goodbye sir"
        if: ${{always()}}
              
